 INSERT INTO CATEGORY ( CATEGORY_NO, CATEGORY_name) VALUES ( category_category_no_seq.nextval, '남성');
  INSERT INTO CATEGORY ( CATEGORY_NO, CATEGORY_name) VALUES ( category_category_no_seq.nextval, '여성');
INSERT INTO SUB_CATEGORY ( SUB_CATEGORY_NO, SUB_CATEGORY_NAME) VALUES ( SUB_category_SUB_category_no_seq.nextval, '아우터');
 INSERT INTO SUB_CATEGORY ( SUB_CATEGORY_NO, SUB_CATEGORY_NAME) VALUES ( SUB_category_SUB_category_no_seq.nextval, '상의');
 INSERT INTO SUB_CATEGORY ( SUB_CATEGORY_NO, SUB_CATEGORY_NAME) VALUES ( SUB_category_SUB_category_no_seq.nextval, '하의');

INSERT INTO COLOR
	( COLOR_NO, COLOR_NAME, COLOR_CODE) VALUES ( COLOR_COLOR_NO_SEQ.NEXTVAL, 'BLACK', '#000000');
INSERT INTO COLOR
	( COLOR_NO, COLOR_NAME, COLOR_CODE) VALUES ( COLOR_COLOR_NO_SEQ.NEXTVAL, 'WHITE', '#FFFFFF');
INSERT INTO COLOR
	( COLOR_NO, COLOR_NAME, COLOR_CODE) VALUES ( COLOR_COLOR_NO_SEQ.NEXTVAL, 'RED', '#FF0000');
INSERT INTO COLOR
	( COLOR_NO, COLOR_NAME, COLOR_CODE) VALUES ( COLOR_COLOR_NO_SEQ.NEXTVAL, 'BLUE', '#0000FF');
INSERT INTO COLOR
	( COLOR_NO, COLOR_NAME, COLOR_CODE) VALUES ( COLOR_COLOR_NO_SEQ.NEXTVAL, 'GREEN', '#00FF00');
INSERT INTO COLOR
	( COLOR_NO, COLOR_NAME, COLOR_CODE) VALUES ( COLOR_COLOR_NO_SEQ.NEXTVAL, 'BROWN', '#B45F04');
    INSERT INTO COLOR
	( COLOR_NO, COLOR_NAME, COLOR_CODE) VALUES ( COLOR_COLOR_NO_SEQ.NEXTVAL, 'GRAY', '#A9BCF5');
    INSERT INTO COLOR
	( COLOR_NO, COLOR_NAME, COLOR_CODE) VALUES ( COLOR_COLOR_NO_SEQ.NEXTVAL, 'BEIGE', '#F6E3CE');
	    INSERT INTO COLOR
	( COLOR_NO, COLOR_NAME, COLOR_CODE) VALUES ( COLOR_COLOR_NO_SEQ.NEXTVAL, 'KHAKI', '#4B610B');
INSERT INTO SIZES
	( SIZE_NO, SIZE_NAME) VALUES ( sizes_size_no_seq.nextval, 'S');
INSERT INTO SIZES
	( SIZE_NO, SIZE_NAME) VALUES ( sizes_size_no_seq.nextval, 'M');
INSERT INTO SIZES
	( SIZE_NO, SIZE_NAME) VALUES ( sizes_size_no_seq.nextval, 'L');
INSERT INTO SIZES
	( SIZE_NO, SIZE_NAME) VALUES ( sizes_size_no_seq.nextval, 'XL');
INSERT INTO SIZES
	( SIZE_NO, SIZE_NAME) VALUES ( sizes_size_no_seq.nextval, 'FREE');