
 INSERT INTO CATEGORY ( CATEGORY_NO, CATEGORY_name) VALUES ( category_category_no_seq.nextval, '남성');
  INSERT INTO CATEGORY ( CATEGORY_NO, CATEGORY_name) VALUES ( category_category_no_seq.nextval, '여성');
INSERT INTO SUB_CATEGORY ( SUB_CATEGORY_NO, SUB_CATEGORY_NAME) VALUES ( SUB_category_SUB_category_no_seq.nextval, '아우터');
 INSERT INTO SUB_CATEGORY ( SUB_CATEGORY_NO, SUB_CATEGORY_NAME) VALUES ( SUB_category_SUB_category_no_seq.nextval, '상의');
 INSERT INTO SUB_CATEGORY ( SUB_CATEGORY_NO, SUB_CATEGORY_NAME) VALUES ( SUB_category_SUB_category_no_seq.nextval, '하의');

INSERT INTO COLOR
	( COLOR_NO, COLOR_NAME, COLOR_CODE) VALUES ( COLOR_COLOR_NO_SEQ.NEXTVAL, 'BLACK', '#000000');
INSERT INTO COLOR
	( COLOR_NO, COLOR_NAME, COLOR_CODE) VALUES ( COLOR_COLOR_NO_SEQ.NEXTVAL, 'WHITE', '#FFFFFF');
INSERT INTO COLOR
	( COLOR_NO, COLOR_NAME, COLOR_CODE) VALUES ( COLOR_COLOR_NO_SEQ.NEXTVAL, 'RED', '#FF0000');
INSERT INTO COLOR
	( COLOR_NO, COLOR_NAME, COLOR_CODE) VALUES ( COLOR_COLOR_NO_SEQ.NEXTVAL, 'BLUE', '#0000FF');
INSERT INTO COLOR
	( COLOR_NO, COLOR_NAME, COLOR_CODE) VALUES ( COLOR_COLOR_NO_SEQ.NEXTVAL, 'GREEN', '#00FF00');
INSERT INTO COLOR
	( COLOR_NO, COLOR_NAME, COLOR_CODE) VALUES ( COLOR_COLOR_NO_SEQ.NEXTVAL, 'BROWN', '#B45F04');
    INSERT INTO COLOR
	( COLOR_NO, COLOR_NAME, COLOR_CODE) VALUES ( COLOR_COLOR_NO_SEQ.NEXTVAL, 'GRAY', '#A9BCF5');
    INSERT INTO COLOR
	( COLOR_NO, COLOR_NAME, COLOR_CODE) VALUES ( COLOR_COLOR_NO_SEQ.NEXTVAL, 'BEIGE', '#F6E3CE');
    INSERT INTO COLOR
	( COLOR_NO, COLOR_NAME, COLOR_CODE) VALUES ( COLOR_COLOR_NO_SEQ.NEXTVAL, 'KHAKI', '#4B610B');
    
    
    
INSERT INTO SIZES
	( SIZE_NO, SIZE_NAME) VALUES ( sizes_size_no_seq.nextval, 'S');
INSERT INTO SIZES
	( SIZE_NO, SIZE_NAME) VALUES ( sizes_size_no_seq.nextval, 'M');
INSERT INTO SIZES
	( SIZE_NO, SIZE_NAME) VALUES ( sizes_size_no_seq.nextval, 'L');
INSERT INTO SIZES
	( SIZE_NO, SIZE_NAME) VALUES ( sizes_size_no_seq.nextval, 'XL');
INSERT INTO SIZES
	( SIZE_NO, SIZE_NAME) VALUES ( sizes_size_no_seq.nextval, 'FREE');
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////                  (1)
insert into product values(product_product_no_seq.nextval, '배색 웜업 자켓', 39000, sysdate, 0, 1, 1);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 6);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);

    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////            (2)
insert into product values(product_product_no_seq.nextval, '벨티드코드', 79000, sysdate, 0, 1, 1);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 7);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);
INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////            (3)
insert into product values(product_product_no_seq.nextval, '발마칸코트', 89000, sysdate, 0, 1, 1);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 7);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);

    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////                         (4)
insert into product values(product_product_no_seq.nextval, '더플 코트', 89000, sysdate, 0, 1, 1);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 4);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 7);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);

 INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////         (5)
insert into product values(product_product_no_seq.nextval, '워크 재킷', 79000, sysdate, 0, 1, 1);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_5.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_5.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 4);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 7);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);

    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////             (6)
insert into product values(product_product_no_seq.nextval, '블루종', 59000, sysdate, 0, 1, 1);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_6.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_6.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 8);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);
    
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////                 (7)
insert into product values(product_product_no_seq.nextval, '후드 윈드브레이커', 79000, sysdate, 0, 1, 1);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_7.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2_1_7_1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3_1_7_2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4_7_3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5_1_7_4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_7.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);


INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 7);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////                 (8)
insert into product values(product_product_no_seq.nextval, '베이직 바사티 재킷', 59000, sysdate, 0, 1, 1);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_8.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2_1_8_1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3_1_8_2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4_1_8_3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5_1_8_4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_6_1_8_5.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_7_1_8_6.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_8_1_8_7.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_9_1_8_8.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_10_1_8_9.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_11_1_8_11.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_12_8_12.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_13_1_8H_10.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_8.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);


INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 4);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 7);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);
    
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
           INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 2, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////                    (9)
insert into product values(product_product_no_seq.nextval, '집업 카디건', 49000, sysdate, 0, 1, 1);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_9.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2_1_9_1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3_1_9_2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4_1_9_3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5_1_9_4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_6_1_9_5.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_7_1_9_6.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_9.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 7);
 INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 8);   
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);

    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 2, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 4, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 3, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 2, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 4, 10);
       INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////             (10)
insert into product values(product_product_no_seq.nextval, '오버핏 집업 점퍼', 59000, sysdate, 0, 1, 1);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_10.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2_1_10_1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3_1_10_2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4_10_3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5_1_10_4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_10.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 8);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);

    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////              bottom (11)
insert into product values(product_product_no_seq.nextval, '코듀로이 카고 와이드 팬츠', 59000, sysdate, 0, 1, 3);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_11.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_11.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 8);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);

    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////      (12)
insert into product values(product_product_no_seq.nextval, '스크레치 슬랙스', 59000, sysdate, 0, 1, 3);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_12.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_12.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
--INSERT INTO PRODUCT_COLOR
--	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 6);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);

    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
--    INSERT INTO STOCK
--	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
--    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 3, 10);
--      INSERT INTO STOCK
--	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
--    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////     (13)
insert into product values(product_product_no_seq.nextval, '남성 조거 팬츠', 49000, sysdate, 0, 1, 3);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_13.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2_1_13_1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 7);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);

    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////                (14)
insert into product values(product_product_no_seq.nextval, '코듀로이 원턱 밴딩 팬츠', 49000, sysdate, 0, 1, 3);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_14.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2_1_14_1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3_1_14_2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_14.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 9);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 9, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 9, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 9, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////                   (15)
insert into product values(product_product_no_seq.nextval, '플리스 액티브 조거팬츠', 49000, sysdate, 0, 1, 3);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_15.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2_1_15_1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3_1_15_2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_15.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 7);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 8);    
    
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 2, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 2, 10);

    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////             (16)
insert into product values(product_product_no_seq.nextval, '치노 팬츠', 49000, sysdate, 0, 1, 3);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_16.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2_1_16_1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3_1_16_2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_16.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 2);
    INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 7);
    INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 9);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);

    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 2, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 4, 10);
              INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 9, 2, 10);
          INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 9, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 9, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////        (17)
insert into product values(product_product_no_seq.nextval, '풀벤딩 스트레이트 슬랙스', 39000, sysdate, 0, 1, 3);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_17.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2_1_17_1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3_1_17_2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4_1_17_3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_17.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
--INSERT INTO PRODUCT_COLOR
--	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 6);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);

    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
--    INSERT INTO STOCK
--	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
--    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 3, 10);
--      INSERT INTO STOCK
--	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
--    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////        (18)
insert into product values(product_product_no_seq.nextval, 'GEORGIA 트랙 스웨이팬츠', 49000, sysdate, 0, 1, 3);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_18.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2_1_18_1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3_1_18_2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4_1_18_3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5_1_18_4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_6_1_18_5.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_18.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////             (19)
insert into product values(product_product_no_seq.nextval, '파라슈트 와이드 팬츠', 59000, sysdate, 0, 1, 3);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_19.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2_1_19_1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3_1_19_2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4_1_19_3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5_1_19_4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_19.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 8);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);

    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////            (20)
insert into product values(product_product_no_seq.nextval, '카고 와이드 팬츠', 49000, sysdate, 0, 1, 3);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_20.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2_1_20_1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3_1_20_2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4_1_20_3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5_1_20_4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_6_1_20_5.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_7_1_20_6.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_8_1_20_7.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_20.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 8);
    INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 9);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 4, 10);
            INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 9, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 9, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 9, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////          (21)
insert into product values(product_product_no_seq.nextval, '플리스 액티브 후드집업', 69000, sysdate, 0, 1, 2);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_21.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_21.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 7);
    INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 8);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);

    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 4, 10);
            INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////         (2)
insert into product values(product_product_no_seq.nextval, '하이넥 절개 스웨트 집업', 39000, sysdate, 0, 1, 2);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_22.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_22.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
--INSERT INTO PRODUCT_COLOR
--	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 6);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);

    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
--    INSERT INTO STOCK
--	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
--    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 3, 10);
--      INSERT INTO STOCK
--	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
--    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////            (23)
insert into product values(product_product_no_seq.nextval, 'GEORGIA 트랙 스웨트셔츠', 59000, sysdate, 0, 1, 2);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_23.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2_1_23_2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3_1_23_3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4_1_23_4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5_1_23_5.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_6_1_23_6.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_7_1_23_7.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_8_1_23_2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_23.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);

    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////            (24)
insert into product values(product_product_no_seq.nextval, '프렌즈 후드풀오버(기모)', 59000, sysdate, 0, 1, 2);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_24.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2_1_24_1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3_1_24_2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4_1_24_4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5_1_24_5.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_6_1_24_3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_24.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 2);
    INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 9);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 4, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 9, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 9, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 9, 4, 10);
    
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////          (25)
insert into product values(product_product_no_seq.nextval, '드라이메쉬 반팔티', 39000, sysdate, 0, 1, 2);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_25.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2_1_25_1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3_1_25_2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4_1_25_3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5_1_25_4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_25.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL ,2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////              (26)
insert into product values(product_product_no_seq.nextval, '오버핏 데님 셔츠(셋업)', 59000, sysdate, 0, 1, 2);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_26.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2_1_26_1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3_1_26_2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4_1_26_3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5_1_26_4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_26.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 4);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////            (27)
insert into product values(product_product_no_seq.nextval, '베이직 스웨트셔츠', 49000, sysdate, 0, 1, 2);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_27.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2_1_27_1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3_1_27_2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4_1_27_3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5_1_27_4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_6_1_27_5.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_7_1_27_6.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_8_1_27_7.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_27.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 2);
    INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 4);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 9);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 2, 10);
    
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 9, 2, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 9, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 9, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////           (28)
insert into product values(product_product_no_seq.nextval, '후드 스웨터', 49000, sysdate, 0, 1, 2);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_28.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2_1_28_1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3_1_28_2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4_1_28_3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5_1_28_4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_6_1_28_5.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_7_1_28_6.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_8_1_28_7.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_28.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 7);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 8);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////  (29)
insert into product values(product_product_no_seq.nextval, '피그먼트 스웨터셔츠', 49000, sysdate, 0, 1, 2);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_29.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2_1_29_1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3_1_29_2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4_1_29_3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5_1_29_4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_6_1_29_5.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_7_1_29_6.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_8_1_29_7.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_9_1_29_8.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_29.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 4);
    INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 9);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
        INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 4, 10);
            INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 9, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 9, 3, 10);
      INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 9, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////    (30)
insert into product values(product_product_no_seq.nextval, '반팔티', 29000, sysdate, 0, 1, 2);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1_30.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2_1_30_1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3_1_30_2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4_1_30_3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5_1_30_4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_30.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
--INSERT INTO PRODUCT_COLOR
--	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 6);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
     INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
--    INSERT INTO STOCK
--	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
--    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 3, 10);
--      INSERT INTO STOCK
--	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
--    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 4, 10);
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
