
 INSERT INTO CATEGORY ( CATEGORY_NO, CATEGORY_name) VALUES ( category_category_no_seq.nextval, '남성');
 INSERT INTO CATEGORY ( CATEGORY_NO, CATEGORY_name) VALUES ( category_category_no_seq.nextval, '여성');
 
 INSERT INTO SUB_CATEGORY ( SUB_CATEGORY_NO, SUB_CATEGORY_NAME) VALUES ( SUB_category_SUB_category_no_seq.nextval, '아우터');
 INSERT INTO SUB_CATEGORY ( SUB_CATEGORY_NO, SUB_CATEGORY_NAME) VALUES ( SUB_category_SUB_category_no_seq.nextval, '상의');
 INSERT INTO SUB_CATEGORY ( SUB_CATEGORY_NO, SUB_CATEGORY_NAME) VALUES ( SUB_category_SUB_category_no_seq.nextval, '하의');
-- INSERT INTO CATEGORY ( CATEGORY_NO, CATEGORY) VALUES ( category_category_no_seq.nextval, 아동);
-- INSERT INTO CATEGORY ( CATEGORY_NO, CATEGORY) VALUES ( category_category_no_seq.nextval, 남성);
-- INSERT INTO CATEGORY ( CATEGORY_NO, CATEGORY) VALUES ( category_category_no_seq.nextval, 남성);
-- INSERT INTO CATEGORY ( CATEGORY_NO, CATEGORY) VALUES ( category_category_no_seq.nextval, 남성);
-- INSERT INTO CATEGORY ( CATEGORY_NO, CATEGORY) VALUES ( category_category_no_seq.nextval, 남성);

INSERT INTO COLOR
	( COLOR_NO, COLOR_NAME, COLOR_CODE) VALUES ( COLOR_COLOR_NO_SEQ.NEXTVAL, 'BLACK', '#000000');
INSERT INTO COLOR
	( COLOR_NO, COLOR_NAME, COLOR_CODE) VALUES ( COLOR_COLOR_NO_SEQ.NEXTVAL, 'WHITE', '#FFFFFF');
INSERT INTO COLOR
	( COLOR_NO, COLOR_NAME, COLOR_CODE) VALUES ( COLOR_COLOR_NO_SEQ.NEXTVAL, 'RED', '#FF0000');
INSERT INTO COLOR
	( COLOR_NO, COLOR_NAME, COLOR_CODE) VALUES ( COLOR_COLOR_NO_SEQ.NEXTVAL, 'BLUE', '#0000FF');
INSERT INTO COLOR
	( COLOR_NO, COLOR_NAME, COLOR_CODE) VALUES ( COLOR_COLOR_NO_SEQ.NEXTVAL, 'GREEN', '#00FF00');
    
    
INSERT INTO SIZES
	( SIZE_NO, SIZE_NAME) VALUES ( sizes_size_no_seq.nextval, 'S');
INSERT INTO SIZES
	( SIZE_NO, SIZE_NAME) VALUES ( sizes_size_no_seq.nextval, 'M');
INSERT INTO SIZES
	( SIZE_NO, SIZE_NAME) VALUES ( sizes_size_no_seq.nextval, 'L');
INSERT INTO SIZES
	( SIZE_NO, SIZE_NAME) VALUES ( sizes_size_no_seq.nextval, 'XL');
INSERT INTO SIZES
	( SIZE_NO, SIZE_NAME) VALUES ( sizes_size_no_seq.nextval, 'FREE');

insert into product values(product_product_no_seq.nextval, '니트', 10000, sysdate, 1000, 1, 2);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_SHIRTS.PNG', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_SHIRTS.JPG', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

insert into product values(product_product_no_seq.nextval, '맨투맨', 2500, sysdate, 100, 2, 2); 
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_SHIRTS.PNG', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_SHIRTS.JPG', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
insert into product values(product_product_no_seq.nextval, '흰티', 1500, sysdate, 100, 1, 2);  
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_SHIRTS.PNG', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_SHIRTS.JPG', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
insert into product values(product_product_no_seq.nextval, '검은티', 1000, sysdate, 100, 2, 2);  
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_SHIRTS.PNG', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_SHIRTS.JPG', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
insert into product values(product_product_no_seq.nextval, '베이직 스웨트셔츠', 19900, sysdate, 100, 1, 2); 
    
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_SHIRTS.PNG', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_SHIRTS.JPG', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 2);   
    
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1);
    INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
    INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
    INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);
    INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5);
    
    
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 1, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 5, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 1, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 2, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 3, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 4, 10);
    INSERT INTO STOCK
	( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
    VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 5, 10);
    
    