insert into product values(product_product_no_seq.nextval, '여성 드레이프 티셔츠', 25900, sysdate, 0, 2, 2);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1shrit.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_1shrit.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 2);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 4);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5);

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 5, 4);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 5, 4);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 5, 4);
--1  

insert into product values(product_product_no_seq.nextval, 'WARMTECH 에브리웨어 긴팔', 25900, sysdate, 0, 2, 2);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1.shrit1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2shrit.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_2shrit.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 7);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1);
    INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
    INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 1, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 2, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 3, 5);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 1, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 1, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 2, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 3, 5);
--2

insert into product values(product_product_no_seq.nextval, '(GEORGIA)자수 스웨트셔츠(기모)', 49900, sysdate, 0, 2, 2);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1shrit.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2.shrit11.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3.shrit2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4.shrit3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_3shrit.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 7);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5);

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 5, 5);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 5, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 5, 5);
--3

insert into product values(product_product_no_seq.nextval, '코튼 반오픈넥 셔츠', 19900, sysdate, 0, 2, 2);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_4shrit.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2.shrit1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3.shrit2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4.shrit3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5.shrit4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_6.shrit5.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_4shrit.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 2);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 4);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5);

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 5, 5);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 5, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 5, 5);
--4

insert into product values(product_product_no_seq.nextval, '발레코어 크롭 스웨트셔츠(기모)', 39900, sysdate, 0, 2, 2);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_5shrit.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2.shrit1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3.shrit2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4.shrit3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_5shrit.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 2);

INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5);

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 5, 10);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 5, 10);
--5

insert into product values(product_product_no_seq.nextval, '(우디)럭비 스웨트셔츠', 35900, sysdate, 0, 2, 2);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_6shrit.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2.shrit1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3.shrit2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4.shrit3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_6shrit.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 5);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 3);
    INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 7);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1);
    INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
    INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
    
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 1, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 5);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5, 1, 5);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5, 2, 5);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5, 3, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3, 1, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3, 2, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3, 3, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 1, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 2, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 3, 5);
--6

insert into product values(product_product_no_seq.nextval, '발레코어 크롭 후드풀오버(기모)', 55900, sysdate, 0, 2, 2);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_7shrit.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2.shrit1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3.shrit2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4.shrit3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_7shrit.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 2);

INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5);

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 5, 10);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 5, 10);
--7

insert into product values(product_product_no_seq.nextval, '터틀넥 풀오버', 15900, sysdate, 0, 2, 2);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_8shrit.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2.shrit1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3.shrit2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4.shrit3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5.shrit4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_8shrit.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 4);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 7);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 8);
INSERT INTO PRODUCT_COLOR
    ( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 2);
INSERT INTO PRODUCT_COLOR
    ( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);

INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5);

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 5, 7);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 5, 7);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 5, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 5, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 5, 10);
--8

insert into product values(product_product_no_seq.nextval, '스윗베어 스웨트셔츠', 39900, sysdate, 0, 2, 2);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_9shrit.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2.shrit1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3.shrit2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4.shrit3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5.shrit4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_9shrit.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 7);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 2);
    INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 5);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5);

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 5, 10);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 5, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5, 5, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 5, 10);
--9

insert into product values(product_product_no_seq.nextval, '(우디)자수 크롭 반팔티', 35900, sysdate, 0, 2, 2);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_10shrit.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2.shrit1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3.shrit2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4.shrit3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_10shrit.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 2);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 7);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5);

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 5, 10);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 5, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 5, 10);
--10

insert into product values(product_product_no_seq.nextval, '코듀로이 플리츠 미니 스커트', 25900, sysdate, 0, 2, 3);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_skirt.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_1skirt.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 8);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);

INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);    

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 1, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 5);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 1, 5);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 2, 5);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 3, 5);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 4, 5);
--11  

insert into product values(product_product_no_seq.nextval, '부츠컷 진', 39900, sysdate, 0, 2, 3);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_2pants.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2.pants1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3.pants2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4.pants3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_2pants.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 4);

INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);    

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 1, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 2, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 3, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 4, 5);
--12

insert into product values(product_product_no_seq.nextval, '와이드 진', 19900, sysdate, 0, 2, 3);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_3pants.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2.pants1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3.pants2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4.pants3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5.pants4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_3.pants4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 4);

INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);    

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 1, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 2, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 3, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 4, 10);
--13

insert into product values(product_product_no_seq.nextval, '핀턱 코튼 와이드 팬츠', 49900, sysdate, 0, 2, 3);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_4pants.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2.pants1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3.pants2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4.pants3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5.pants4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_4pants.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 8);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 6);

INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3); 
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);    

 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 1, 5);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 2, 5);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 3, 5);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 4, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 1, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 3, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 2, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 4, 5);
--14

insert into product values(product_product_no_seq.nextval, '미니 스커트', 45900, sysdate, 0, 2, 3);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_5skirt.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2.skirt1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3.skirt2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4.skirt3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_5.skirt.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 8);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 7);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 6);

INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);    

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 1, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 2, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 3, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 4, 5);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 4, 5);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 3, 5);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 2,5);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 1, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 1, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 5);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 1, 5);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 2, 5);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 3, 5);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 4, 5);
--15

insert into product values(product_product_no_seq.nextval, '롱 와이드 슬랙스', 35900, sysdate, 0, 2, 3);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_6.pants.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_6.pants.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 5);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 7);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4);    

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 1, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 4, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5, 1, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5, 2, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5, 3, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5, 4, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 1, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 2, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 3, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 4, 10);
--16

insert into product values(product_product_no_seq.nextval, '크롭 와이드 슬랙스', 25900, sysdate, 0, 2, 3);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_7.pants.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2.pants1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3.pants2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4.pants3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5.pants4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_7.pants.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 8);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 7);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);    

INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);    

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 1, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 1, 8);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 2, 8);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 3, 8);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 1, 7);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 2, 7);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 3, 7);
--17

insert into product values(product_product_no_seq.nextval, '풀밴딩 스트레치 부츠컷', 19900, sysdate, 0, 2, 3);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_8.pants.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2.pants1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3.pants2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4.pants3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5.pants4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_8.pants.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 6);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 8);
INSERT INTO PRODUCT_COLOR
    ( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);


INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5);

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 5, 8);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 5, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 5, 8);
--18

insert into product values(product_product_no_seq.nextval, '플리츠 와이드 팬츠', 15900, sysdate, 0, 2, 3);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_9.pants.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2.pants1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3.pants2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4.pants3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5.pants4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_9.pants.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5);

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 5, 17);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 5, 17);

--19

insert into product values(product_product_no_seq.nextval, '세미와이드 스웨트팬츠', 25900, sysdate, 0, 2, 3);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_10.pants.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2.pants1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3.pants2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4.pants3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5.pants4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_10.pants.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 6);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 7);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 2);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 4);    

INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5);
    

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 5, 15);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 5, 15);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 5, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 5, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 5, 10);
--20

insert into product values(product_product_no_seq.nextval, '탈착 칼라 경량 퀄팅 재킷', 75900, sysdate, 0, 2, 1);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_1outer.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_1outer.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 2);

INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5);

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 5, 20);

--21  

insert into product values(product_product_no_seq.nextval, '프린지 트위드재킷', 69900, sysdate, 0, 2, 1);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_2outer.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2.outer1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3.outer2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 2);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 5);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5);

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 5, 10);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 5, 12);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5, 5, 7);
--22

insert into product values(product_product_no_seq.nextval, '후드 크롭 항공 점퍼', 55900, sysdate, 0, 2, 1);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_3outer.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_3outer.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 5);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);

INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5);

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5, 5, 10);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 5, 15);

--23

insert into product values(product_product_no_seq.nextval, '덤블 숏 더플 코트', 25900, sysdate, 0, 2, 1);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_4outer.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2.outer1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3.outer2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4.outer3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_4outer.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 6);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 8);

INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5);

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 5, 10);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 5, 15);

--24

insert into product values(product_product_no_seq.nextval, '후드 야상 점퍼', 29900, sysdate, 0, 2, 1);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_5outer.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_5outer.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 5);

INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5);

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 5, 10);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5, 5, 8);
--25

insert into product values(product_product_no_seq.nextval, '(우디)자수 브이넥 카디건', 19900, sysdate, 0, 2, 1);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_6outer.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2.outer1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3.outer2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4.outer3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_6outer.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 4);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 7);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5);

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 5, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 4, 5, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 5, 12);
--26

insert into product values(product_product_no_seq.nextval, '덤블칼라 탈착 숏코트', 39900, sysdate, 0, 2, 1);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_7outer.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2.outer1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3.outer2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4.outer3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_7outer.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 6);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 8);

INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);    

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 2, 9);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 3, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 2, 12);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 8, 3, 10);
--27

insert into product values(product_product_no_seq.nextval, '아란 더플 후드 카디건', 79900, sysdate, 0, 2, 1);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_8outer.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2.outer1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3.outer2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4.outer3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5.outer4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_8outer.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 2);

INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);    

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 11);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 9);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 2, 5);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 3, 11);
--28

insert into product values(product_product_no_seq.nextval, '여성 씬 라이트 패쪼', 49900, sysdate, 0, 2, 1);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_9outer.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2.outer1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3.outer2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4.outer3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_5.outer4.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_9outer.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 2);

INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 3);

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 1, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 2, 10);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 3, 7);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 1, 8);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 2, 9);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 2, 3, 10);
--29

insert into product values(product_product_no_seq.nextval, '브이넥 카디건', 79900, sysdate, 0, 2, 1);  

INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_1_10outer.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_2.outer1.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_3.outer2.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'TITLE_4.outer3.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);
INSERT INTO PRODUCT_IMAGE
( PRODUCT_IMAGE_NO, PRODUCT_IMAGE_NAME, PRODUCT_NO)
VALUES ( PRODUCT_IMAGE_PRODUCT_IMAGE_NO_SEQ.NEXTVAL, 'DETAIL_1_10outer.jpg', PRODUCT_PRODUCT_NO_SEQ.CURRVAL);

INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 6);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 7);
INSERT INTO PRODUCT_COLOR
	( PRODUCT_COLOR_NO, PRODUCT_NO, COLOR_NO) VALUES ( PRODUCT_COLOR_PRODUCT_COLOR_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL , 1);
INSERT INTO PRODUCT_SIZE
	( PRODUCT_SIZE_NO, PRODUCT_NO, SIZE_NO) VALUES ( PRODUCT_SIZE_PRODUCT_SIZE_NO_SEQ.NEXTVAL,PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 5);

INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 6, 5, 8);
 INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 7, 5, 7);
INSERT INTO STOCK
( STOCK_NO, PRODUCT_NO, COLOR_NO, SIZE_NO, STOCK_QTY) 
VALUES ( STOCK_STOCK_NO_SEQ.NEXTVAL, PRODUCT_PRODUCT_NO_SEQ.CURRVAL, 1, 5, 12);
